NEW_SESSION = 'new_session'
NEW_USER = 'new_user'
NEW_JOB = 'new_job'
SESSION_STAGED = 'session_staged'
SESSION_CHECKIN = 'session_checked_in'
SESSION_RESULTS = 'session_results'
NEW_LISTENER = 'new_listener'
SERVER_STATS = 'server_stats'
